name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 6
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: npm test
