name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Build and Test
      run: |
        npm ci
        npm run build
        if [ "${{ runner.os }}" == "Windows" ]; then
          npm test
        elif [ "${{ runner.os }}" == "macOS" ]; then
          npm test --browsers chrome,safari
        else
          xvfb-run --auto-servernum npm test
        fi
      shell: bash
